---
title: "Plots"
author: "matishalin patel"
date: "28/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
```{r, include=FALSE}
library(ggplot2)
library(tidyverse)
options(tidyverse.quiet = TRUE)
my_theme <- theme_bw() + 
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank()
  )
```


```{r, include=FALSE}
dat <- read_csv('../results/190721_fullrange.csv') %>% 
  filter(collapsed!=TRUE, err<=1E-6)
# %>%
#   filter(q==5, n==3)
```

## X and Y with Relatedness

```{r , include=FALSE}
plotDat <- dat %>% filter(n==3&q==5, epsilon==5, stab==5) %>% 
  # filter(force==0|(force!=0&err<1E-6)) %>%
  group_by(d, force, ratio, fixed) %>%
  summarise(
    Cooperation = mean(indAvgX, na.rm=T),
    Conflict = mean(groupAvgY, na.rm=T),
    Relatedness = mean(avgR, na.rm=T),
    Harshness = as.factor(1-ratio)
  ) %>%
  gather("Trait", "Investment", 
         Cooperation, Conflict) %>%
  filter(
         # epsilon%in%c(1,5,10),
         ratio%in%c(0.1, 0.5, 0.9),
         # stab%in%c(5, 10, 15)
         ) %>%
  ungroup()
```
```{r }
ggplot(plotDat %>% filter(force==0.03)) +
  facet_wrap(~Trait, scales="free") +
  geom_path(aes(Relatedness, 
                Investment, 
                linetype=Harshness), size=1) +
  my_theme
```

## X and Y with Encounter Rate

```{r, include=FALSE}
plotDat <- dat %>% filter(n==3&q==5, d>0.1, d<0.9, stab==10) %>%
  # filter(force==0|(force!=0&err<1E-6)) %>%
  group_by(force, ratio, epsilon, fixed) %>%
  summarise(
    Cooperation = mean(indAvgX, na.rm=T),
    Conflict = mean(indAvgY, na.rm=T),
    EncounterRate = epsilon,
    Harshness = as.factor(1-ratio)
  ) %>%
  gather("Trait", "Investment", 
         Cooperation, Conflict) %>%
  filter(
         # epsilon%in%c(1,5,10),
         ratio%in%c(0.1, 0.5, 0.9),
         # stab%in%c(5, 10, 15)
         ) %>%
  ungroup()
```
```{r}
ggplot(plotDat %>% filter(force==0.03)) +
  facet_wrap(~Trait, scales="free") +
  geom_path(aes(EncounterRate, 
                Investment, 
                linetype=Harshness), size=1) +
  my_theme
```

## Relatedness and Mortality 
```{r, include=FALSE}
plotDat <- dat %>% filter(n==3&q==5, epsilon==5) %>%
  # filter(force==0|(force!=0&err<1E-6)) %>%
  group_by(d, force, ratio, fixed) %>%
  summarise(
    Mortality = mean(avgMort, na.rm=T),
    Relatedness = mean(avgR, na.rm=T),
    Harshness = as.factor(1-ratio)
  ) %>%
  filter(
         # epsilon%in%c(1,5,10),
         ratio%in%c(0.1, 0.5, 0.9),
         # stab%in%c(5, 10, 15)
         ) %>%
  ungroup()
```
```{r}
ggplot(plotDat %>% filter(force==0.03)) +
  # facet_wrap(~d)+
  geom_path(aes(Relatedness, 
                Mortality, 
                linetype=Harshness), size=1) +
  my_theme
```

## Effect of Quality level on traits

```{r}
td <- dat %>% 
  filter(q==5, n==3, force==0.03) %>%
  # filter(q==5, n==3, epsilon%in%c(5,10),d==0.5, ratio==0.5, stab==10, force==0.03) %>%
  pivot_longer(
    cols = matches("(t[XYF])(\\d)(\\d\\b)"),
    names_to = c("Trait", "Quality", "Size"),
    names_pattern = "(t[XYF])(\\d)(\\d\\b)",
    values_to = "Investment"
  ) %>% filter(!is.na(Investment), Size>0) %>%
  select(Trait, Investment, Quality, Size, d, epsilon, ratio, stab) %>%
  pivot_wider(names_from = Trait, values_from=Investment) %>%
  mutate(
    Size = as.numeric(Size),
    Quality = as.numeric(Quality)
  ) %>%
  group_by(d, epsilon, ratio, stab) %>%
  mutate(
    normF = tF/(sum(tF)),
    reg = normF*Size,
    tXi = (tX * reg) / sum(reg),
    tYi = (tY * reg) / sum(reg)
  )
  
```
```{r}
plotDat <- td %>% filter(d==0.5, epsilon==5, stab==10) %>%
  pivot_longer(
    cols=all_of(c("tX", "tY")),
    names_to = "Trait",
    values_to = "Investment"
  ) %>%
  mutate(
         Harshness = as.factor(1-ratio)
  ) %>%
  filter( 
         Harshness%in%c(0.1, 0.4, 0.5, 0.6, 0.9),
         # stab%in%c(5, 10, 15),
         # Size>0
  ) %>% 
  ungroup()
  
plotDat$Trait <- recode_factor(plotDat$Trait,
                        tX="Cooperation", 
                        tY="Conflict")
```
```{r}
ggplot(plotDat) + 
  facet_grid(Harshness~Trait, scales="free_y") +
  geom_line(aes(Quality, Investment, 
                linetype=as.factor(Size)),
            size=1) +
  my_theme
```

## Effect of Size level on traits
```{r}
td <- dat %>% 
  # filter(q==3, n==5, force==0.03) %>% distinct() %>%
  filter(q==3, n==5, epsilon%in%c(5), force==0.03) %>%
  pivot_longer(
    cols = matches("(t[XYF])(\\d)(\\d\\b)"),
    names_to = c("Trait", "Quality", "Size"),
    names_pattern = "(t[XYF])(\\d)(\\d\\b)",
    values_to = "Investment"
  ) %>% filter(!is.na(Investment), Size>0) %>%
  select(Trait, Investment, Quality, Size, d, epsilon, ratio, stab) %>%
  pivot_wider(names_from = Trait, values_from=Investment) %>%
  mutate(
    Size = as.numeric(Size),
    Quality = as.numeric(Quality)
  ) %>%
  group_by(d, epsilon, ratio, stab) %>%
  mutate(
    normF = tF/(sum(tF)),
    reg = normF*Size,
    tXi = (tX * reg) / sum(reg),
    tYi = (tY * reg) / sum(reg)
  )
  
```
```{r}
plotDat <- td %>% filter(d==0.5, epsilon==5, stab==10) %>%
  pivot_longer(
    cols=all_of(c("tX", "tY")),
    names_to = "Trait",
    values_to = "Investment"
  ) %>%
  mutate(
         Harshness = as.factor(1-ratio)
  ) %>%
  filter( 
         Harshness%in%c(0.1, 0.5, 0.9),
         # stab%in%c(5, 10, 15),
         # Size>0
  ) %>% 
  ungroup()
  
plotDat$Trait <- recode_factor(plotDat$Trait,
                        tX="Cooperation", 
                        tY="Conflict")
```
```{r}
ggplot(plotDat%>%filter(Harshness==0.5)) + 
  facet_wrap(~Trait, scales="free_y") +
  geom_line(aes(Size, Investment, 
                linetype=as.factor(Quality)),
            size=1) +
  my_theme
```

## Effect of Harshness on Traits 

```{r , include=FALSE}
plotDat <- dat %>%
  # filter(force==0|(force!=0&err<1E-6)) %>%
  group_by(d, force, ratio, epsilon, fixed, stab) %>%
  summarise(
    Cooperation = mean(indAvgX, na.rm=T),
    Conflict = mean(indAvgY, na.rm=T),
    Harshness = as.numeric(1-ratio),
    Dispersal = as.factor(d)
  ) %>%
  gather("Trait", "Investment", 
         Cooperation, Conflict) %>%
  filter(
         epsilon%in%c(1,5,8),
         d%in%c(0.1, 0.5, 0.9),
         # stab%in%c(5, 10, 15)
         ) %>%
  ungroup()
```
```{r }
ggplot(plotDat %>% 
         filter(force==0.03,  epsilon==5, stab==10)) +
  facet_wrap(~Trait, scales="free") +
  geom_path(aes(Harshness, 
                Investment, linetype=as.factor(d)), size=1) +
  my_theme

ggplot(plotDat %>% 
         filter(force==0.03,  d==0.5, stab==10)) +
  facet_wrap(~Trait, scales="free") +
  geom_path(aes(Harshness, 
                Investment, linetype=as.factor(epsilon)), size=1) +
  my_theme
```

## Effect of Stability on Traits 

```{r , include=FALSE}
plotDat <- dat %>%
  # filter(force==0|(force!=0&err<1E-6)) %>%
  group_by(d, force, stab, fixed, epsilon, ratio) %>%
  summarise(
    Cooperation = mean(indAvgX, na.rm=T),
    Conflict = mean(indAvgY, na.rm=T),
    Stability = as.numeric(stab),
    Dispersal = as.factor(d)
  ) %>%
  gather("Trait", "Investment", 
         Cooperation, Conflict) %>%
  filter(
         # epsilon%in%c(1,5,10),
         d%in%c(0.1, 0.5, 0.9),
         # stab%in%c(5, 10, 15)
         ) %>%
  ungroup()
```
```{r }
ggplot(plotDat %>% filter(force==0.03, ratio==0.5, epsilon==5)) +
  facet_wrap(~Trait, scales="free") +
  geom_path(aes(Stability, 
                Investment, 
                linetype=Dispersal), size=1) +
  my_theme
```

## Effect of Harshness on Resource Value
```{r , include=FALSE}
plotDat <- dat %>%
  # filter(force==0|(force!=0&err<1E-6)) %>%
  group_by(d, force, ratio, fixed) %>%
  summarise(
    Value = mean(qVal, na.rm=T),
    Harshness = as.numeric(1-ratio),
    Dispersal = as.factor(d)
  ) %>%
  filter(
         # epsilon%in%c(1,5,10),
         d%in%c(0.1, 0.5, 0.9),
         # stab%in%c(5, 10, 15)
         ) %>%
  ungroup()
```
```{r }
ggplot(plotDat %>% filter(force==0.03)) +
  geom_path(aes(Harshness, 
                Value, 
                linetype=Dispersal), size=1) +
  my_theme
```

## Effect of Harshness on Productivity
```{r , include=FALSE}
plotDat <- td %>%
  # filter(force==0|(force!=0&err<1E-6)) %>%
  group_by(d, force, ratio, fixed) %>%
  summarise(
    Value = mean(Pfi, na.rm=T),
    Harshness = as.numeric(1-ratio),
    Dispersal = as.factor(d)
  ) %>%
  filter(
         # epsilon%in%c(1,5,10),
         d%in%c(0.1, 0.5, 0.9),
         # stab%in%c(5, 10, 15)
         ) %>%
  ungroup()
```
```{r }
ggplot(plotDat %>% filter(force==0.03)) +
  geom_path(aes(Harshness, 
                Value, 
                linetype=Dispersal), size=1) +
  my_theme
```